# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_user_confirm_password'),
        ('courses', '0002_auto_20161114_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(related_name='courses', to='logreg.User'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
